version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: go_webstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - 5432:5432
